version = 1

test_patterns = ["src/__tests__/**/?(*.)+(spec|test|unit).[tj]s?(x)"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]